// Copyright 2023 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics -i 未标题-1.jpg -f rgb565`

#pragma once

#include <qp.h>

extern const uint32_t gfx_____1_length;
extern const uint8_t  gfx_____1[41008];
